name: NPM Audit Fix Run

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Specify a base branch"
        required: false
        default: "main"
      script:
        description: "Specify a script to run after audit fix"
        required: false
        default: "yarn build"
      package_manager:
        description: "Specify package manager (npm or yarn)"
        required: false
        default: "yarn"

  schedule:
    - cron: "0 0 * * 1"

jobs:
  audit-fix:
    uses: step-security/reusable-workflows/.github/workflows/audit_fix.yml@v1
    with:
      base_branch: ${{ inputs.base_branch || 'main' }}
      script: ${{ inputs.script || 'yarn build' }}
      package_manager: ${{inputs.package_manager || 'yarn' }}

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write
